user abc;

include /config/worker_processes.conf;

pcre_jit on;

error_log /config/logs/nginx/error.log;

include /etc/nginx/modules/*.conf;
include /etc/nginx/conf.d/*.conf;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    resolver 127.0.0.11 valid=30s;

    server_tokens off;
    client_max_body_size 0;
    sendfile on;
    tcp_nopush on;
    gzip_vary on;

    access_log /config/logs/nginx/access.log;

    fastcgi_connect_timeout 60s;
    fastcgi_send_timeout 1800s;
    fastcgi_read_timeout 1800s;

    include /etc/nginx/http.d/*.conf;

    port_in_redirect on;

    server {
        listen 80 default_server;
        listen [::]:80 default_server;

        server_name _;

        set $root /app/www/public;
        if (!-d /app/www/public) {
            set $root /config/www;
        }

        index index.php;

        location = ${BASE_URL} {
            return 301 $scheme://$http_host${BASE_URL}/;
        }

        location ${BASE_URL}/ {
            alias $root/;
            index index.php;
            try_files $uri $uri/ /index.php$is_args$args;
        }

        location ~ ^${BASE_URL}/crons/ {
            return 403;
        }

        location ~ ^${BASE_URL}/startup\.php$ {
            return 403;
        }

        location ~ ^${BASE_URL}/(.+\.php)$ {
            alias $root/;
            fastcgi_split_path_info ^${BASE_URL}/(.+\.php)(.*)$;
            fastcgi_pass 127.0.0.1:9000;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $root/$1;
            fastcgi_index index.php;
        }

        location /health {
            return 200 'healthy';
            add_header Content-Type text/plain;
        }

        location ~ /\.ht {
            deny all;
        }
    }
}

daemon off;
pid /run/nginx.pid;
