#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ -z ${LSIO_READ_ONLY_FS} ]] && [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    lsiown -R abc:abc \
        /var/lib/nginx

    chmod -R 644 /etc/logrotate.d
fi

if [[ -f "/config/logs/logrotate.status" ]]; then
    chmod 600 /config/logs/logrotate.status
fi

if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    if [[ -d "/config/logs" ]]; then
        lsiown -R abc:abc \
            /config/logs
    fi

    if [[ -f "/config/worker_processes.conf" ]]; then
        lsiown abc:abc \
            /config/worker_processes.conf
    fi
fi
